apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: Opaque
data:
    mysql-root-password: MTIzNA==
    mysql-user: dXNlcjE=
    mysql-user-password: YWRtaW4=
    mysql-database: d29yZHByZXNzLXByb2plY3Q=
