apiVersion: v1
kind: Service
metadata:
    name: mysql-service
    labels:
        app: blog
spec:
    ports:
      - protocol: TCP
        port: 6060
        targetPort: 5080
    clusterIP: None
    selector:
        app: blog
        run: mysql
